parameters:
    app.admin_email: '%env(ADMIN_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\SecurityCodeService:
        arguments:
            $adminEmail: '%app.admin_email%'
